//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&quot;content&quot;&gt;
        ///	&lt;img class=&quot;photo&quot; src=&quot;{photo_100}&quot; alt=&quot;Изображение профиля&quot;/&gt;
        ///	&lt;div class=&quot;user_info&quot;&gt;
        ///		&lt;p&gt;{first_name}&lt;/p&gt;
        ///		&lt;p&gt;{last_name}&lt;/p&gt;
        ///		&lt;div class=&quot;additional_info&quot;&gt;
        ///			&lt;p&gt;{bdate}&lt;/p&gt;
        ///			&lt;p&gt;{sex}&lt;/p&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;additional_info&quot;&gt;
        ///		&lt;div class=&quot;university_info&quot;&gt;
        ///			&lt;p&gt;{university}&lt;/p&gt;
        ///			&lt;p&gt;{faculty}&lt;/p&gt;
        ///			&lt;p&gt;{chair}&lt;/p&gt;
        ///		&lt;/div&gt;
        ///		&lt;div class=&quot;social_info&quot;&gt;
        ///			&lt;div&gt;
        ///				&lt;p&gt;{city}&lt;/p&gt;
        ///				&lt;p&gt;{addr}&lt;/p&gt;
        ///			&lt;/div&gt;
        ///			&lt;div class=&quot;phone&quot;&gt;				
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fac_cha {
            get {
                object obj = ResourceManager.GetObject("fac_cha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facebook_logo {
            get {
                object obj = ResourceManager.GetObject("facebook_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot;&gt;
        ///    &lt;title&gt;{list_name}&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Threading.Tasks;
        ///using System.Reflection;
        ///
        ///namespace ChangeMe_Namespace
        ///{
        ///    public class City
        ///    {
        ///        public int city_id { get; set; }
        ///        public string city_title { get; set; }
        ///    }
        ///
        ///    public class Contacts
        ///    {
        ///        public string mobile_phone { get; set; }
        ///        public string home_phone { get; set; }
        ///        public HashSet&lt;string&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Human_class {
            get {
                return ResourceManager.GetString("Human_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap instagram_logo {
            get {
                object obj = ResourceManager.GetObject("instagram_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap livejournal_logo {
            get {
                object obj = ResourceManager.GetObject("livejournal_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap miet_logo {
            get {
                object obj = ResourceManager.GetObject("miet_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok_logo {
            get {
                object obj = ResourceManager.GetObject("ok_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skype_logo {
            get {
                object obj = ResourceManager.GetObject("skype_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @page {
        ///  size: A4;
        ///}
        ////*
        ///@page :left {
        ///  margin-left: 3cm;
        ///}
        ///
        ///@page :right {
        ///  margin-left: 3cm;
        ///}
        ///*/
        ///body {
        ///	display: flex;
        ///	flex-direction: column;
        ///	align-items: center;
        ///	justify-content: center;
        ///}
        ///
        ///.content {
        ///    display: flex;
        ///    flex-wrap: wrap;
        ///    border-bottom: 1px solid #888;
        ///	padding: 1px;
        ///}
        ///
        ///.photo {
        ///    float: left;
        ///    width: 100px;
        ///    height: 100px;
        ///	margin: 1px;
        ///}
        ///
        ///p {
        ///	margin: 0px;
        ///}
        ///
        ///.user_info {
        ///	width: 130px;
        ///    font-size: 20px;
        ///	margin: 1px 4px; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap twitter_logo {
            get {
                object obj = ResourceManager.GetObject("twitter_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] user_agents {
            get {
                object obj = ResourceManager.GetObject("user_agents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vk_logo {
            get {
                object obj = ResourceManager.GetObject("vk_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
